### ISSUE TITLE
Please Remove CS 155 Code from GitHub

### ISSUE THREAD

**Issue by tdeitch** [rmferrer/cs155#1]
Hi Rafael,

I noticed that your code for CS 155 Project 3 is up on GitHub:
https://github.com/rmferrer/cs155/

Please remove the code from GitHub. The CS Honor Code (Rule 2) asks
students not to post solutions on public websites:
http://csmajor.stanford.edu/HonorCode.shtml

Thanks, and hope you enjoyed the class,

Trey Deitch
CS 155 TA

**Comment by rmferrer** [comment]
resolved.
